# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
# For tabs in the control_sidebar (right screen) add the 'control_sidebar' config key:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md

admin_lte:
    options:
        skin: skin-black
        fixed_layout: false
        boxed_layout: false
        collapsed_sidebar: false
        mini_sidebar: true
    theme:
        widget:
            type: warning
            bordered: true
            collapsible: true
            collapsible_title: 'Collapse'
            removable: false
            removable_title: 'Remove'
            solid: false
            use_footer: false
        button:
            type: 'primary'
            size: false
    control_sidebar:
        settings:
            icon: fas fa-cogs
            controller: 'App\Controller\AdminController::userPreferences'

    knp_menu:
        enable: true

    routes:
        adminlte_welcome: main_home
        adminlte_login: app_login
        adminlte_profile: monProfile
        adminlte_login_check: fos_user_security_check
        adminlte_registration: app_register
        #adminlte_password_reset: fos_user_resetting_request
        adminlte_message: main_home
        adminlte_messages: main_home
        adminlte_notification: main_home
        adminlte_notifications: main_home
        adminlte_task: main_home
        adminlte_tasks: main_home
