artgris_file_manager:
  web_dir: public
  conf:
    default:
      dir: "../public/uploads/"
      tree: true
      view: thumbnail
    private:
      dir: "../public/private/"
      upload:
        max_width: 10
    perso:
      service: "custom_service"