artgris_file_manager:
  web_dir: public
  conf:
    main:
      dir: "../public/uploads/"
      tree: false
    private:
      dir: "../public/private/"
      upload:
        max_width: 10
    perso:
      service: "custom_service"