parameters:
    ressource_image_directory: '%kernel.project_dir%/public/uploads/ressources/images'
    pole_emploi_client_id: '%env(POLE_EMPLOI_CLIENT_ID)%'
    pole_emploi_client_secret: '%env(POLE_EMPLOI_CLIENT_SECRET)%'
    pole_emploi_scope: '%env(POLE_EMPLOI_SCOPE)%'
    artgris_file_manager:
        web_dir: "../public/uploads"
        conf:
            main:
                dir: "../public/uploads/"
                tree: false
            bc:
                dir: '../public/uploads/Bilan de Competences'
                tree: false
            vae:
                dir: '../public/uploads/VAE'
                tree: false
            perso:
                service: "custom_filemanager_config"


services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    archimed.type.ressource_image:
        class: App\Form\Type\RessourceImageType
        arguments: ['%ressource_image_directory%']
        tags: [form.type]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    custom_filemanager_config:
        class: App\Service\FileManagerConfService
        public: true
